
@ECHO OFF
cls
set PYTHONDONTWRITEBYTECODE=1 
REM   default is #ECHO OFF, cls (clear screen), and disable .pyc files 
REM   for debugging REM @ECHO OFF line above to see commands 
REM -------------------------------------------------

REM run_v5_1.bat generated by FTOT run.bat upgrade tool
REM =================================================
       
 
REM ==============================================
REM ======== ENVIRONMENT VARIABLES ===============
REM ==============================================
set PYTHON="C:\FTOT\python3_env\python.exe"
set FTOT="c:\ftot-scr\program\ftot.py"
set XMLSCENARIO="C:\ftot-SCR\scenarios\ForestResiduals_SCR\scenario.xml"


REM ==============================================
REM ======== RUN THE FTOT SCRIPT =================
REM ==============================================

REM  SETUP: SETUP FTOT FOR THE SCENARIO
%PYTHON% %FTOT% %XMLSCENARIO% s || exit /b

REM  FACILITIES: ADD FACILITIES LOCATIONS AND
REM  COMMODITY DATA FILES TO THE SCENARIO
%PYTHON% %FTOT% %XMLSCENARIO% f || exit /b

REM  CONNECTIVITY: CONNECT THE FACILITIES TO THE NETWORK AND
REM  EXPORT THE FROM GIS TO NETWORKX MODULE
%PYTHON% %FTOT% %XMLSCENARIO% c || exit /b

REM  GRAPH: CREATE THE NETWORKX GRAPHS FROM THE
REM  NETWORK AND FACILTIIES
%PYTHON% %FTOT% %XMLSCENARIO% g || exit /b

REM RESILIENCE: EVALUATE SCENARIOS
%PYTHON% %FTOT% %XMLSCENARIO% oscr || exit /b

REM  POST-PROCESSING: POST PROCESS OPTIMAL RESULTS AND PREPARE REPORTING
%PYTHON% %FTOT% %XMLSCENARIO% p || exit /b

REM  REPORT: CREATE REPORTS OF THE CONFIGURATION, RESULTS, AND
REM  WARNINGS FROM THE RUN
%PYTHON% %FTOT% %XMLSCENARIO% d || exit /b

REM  MAPS: GENERATE MAPS OF THE SCENARIO FOR EACH STEP
%PYTHON% %FTOT% %XMLSCENARIO% m || exit /b

REM  OPTIONAL MAPPING STEP FOR TIME AND COMMODITY DISTANCES
REM %PYTHON% %FTOT% %XMLSCENARIO% m2 || exit /b
